{
    "user_role": "user",
    "email": "1122aabb@shootmail.com",
    "applied": "No",
    "if_you_are_currently_a_va_employee_check_the_box_includes_work_studyinternship": "Yes",
    "hasLetter": "No",
    "letterDate": "12/10/2020",
    "conditionsListed": "djdidkfjkdodkdkdodiif",
    "have_you_ever_field_a_claim_with_va": "",
    "did_you_serve_since_9112001_yes": "yes",
    "currently_homeless_yes": "yes",
    "risk_of_becoming_homeless_yes": "yes",
    "serve_under_another_name_yes": "yes",
    "your_living_situation_fleeing": "yes",
    "your_living_situation_2_other": "yes",
    "branch_of_service_army": "yes",
    "": "yes",
    "most_recent_active_service_month_3": "02",
    "most_recent_active_service_day_3": "02",
    "most_recent_active_service_year_3": "1960",
    "most_recent_active_service_exit_date_month": "03",
    "most_recent_active_service_exit_date_day": "03",
    "most_recent_active_service_exit_date_year": "2000",
    "place_of_last_or_anticipated_separation_1": "afganistan  vietnam",
    "veterans_email_primary": "1122aabb@shootmail.com",
    "veterans_email_optional": "3344ccdd@firemail.com",
    "veterans_international_phone": "111111111111111",
    "veteran_service_member_first_fname": "titan",
    "veteran_service_member_middle_mname": "n",
    "veteran_service_member_last_lname": "gold",
    "international_phone_number": "111111111111111",
    "va_file_number": "",
    "veterans_ssn_part1": "123",
    "veterans_ssn_part2": "45",
    "veterans_ssn_part3": "6789",
    "veterans_telephone_area_code": "111",
    "veterans_telephone_operator_code": "222",
    "veterans_telephone_line_number": "3333",
    "service_number_dod_id_number": "0987654321",
    "other_specify": "",
    "other_specify_2": "house will be lost",
    "veterans_dob_month": "01",
    "veterans_dob_day": "01",
    "veterans_dob_year": "1940",
    "veterans_mailing_address": "7th hells angel avenue",
    "veterans_city": "los angeles",
    "veterans_state": "ca",
    "veterans_country": "us",
    "veterans_zip_code": "12345",
    "veterans_postal_code": "0987",
    "veterans_apt_unit": "5020",
    "18b_list_the_other_names_you_served_under": "john f wick",
    "placeOfService": "djdorogngkdokf",
    "activeDutyOrders": "",
    "vaHealthCare": "Yes",
    "vaDirectDeposit": "Yes",
    "current_disabilityiesrow1": "PTSD",
    "approximate_date_disabilityies_began_or_worsenedrow1": "2022-2024",
    "explain_how_the_disabilityies_relates_to_the_inservice_eventexposureinjuryrow1": "firooyotoeowns",
    "if_due_to_exposure_event_or_injury_please_specify_eg_agent_orange_radiation_burn_pitsrow1": "worotjgkcmdd",
    "current_disabilityiesrow2": "INSOMNIA",
    "approximate_date_disabilityies_began_or_worsenedrow2": "2020-2022",
    "explain_how_the_disabilityies_relates_to_the_inservice_eventexposureinjuryrow2": "foeoejf",
    "if_due_to_exposure_event_or_injury_please_specify_eg_agent_orange_radiation_burn_pitsrow2": "xododnfn",
    "current_disabilityiesrow3": "SCIATICA",
    "approximate_date_disabilityies_began_or_worsenedrow3": "2016-2018",
    "explain_how_the_disabilityies_relates_to_the_inservice_eventexposureinjuryrow3": "gkfodkf",
    "if_due_to_exposure_event_or_injury_please_specify_eg_agent_orange_radiation_burn_pitsrow3": "foeoekf",
    "current_disabilityiesrow4": "SINUSITIS",
    "approximate_date_disabilityies_began_or_worsenedrow4": "2014-2016",
    "explain_how_the_disabilityies_relates_to_the_inservice_eventexposureinjuryrow4": "tkroeorjf",
    "if_due_to_exposure_event_or_injury_please_specify_eg_agent_orange_radiation_burn_pitsrow4": "toroeoeng",
    "current_disabilityiesrow5": "TINNITUS",
    "approximate_date_disabilityies_began_or_worsenedrow5": "2018-2020",
    "explain_how_the_disabilityies_relates_to_the_inservice_eventexposureinjuryrow5": "fifornrnnf",
    "if_due_to_exposure_event_or_injury_please_specify_eg_agent_orange_radiation_burn_pitsrow5": "fueieikrnf",
    "current_disabilityiesrow6": "ANXIETY",
    "approximate_date_disabilityies_began_or_worsenedrow6": "2012-2014",
    "explain_how_the_disabilityies_relates_to_the_inservice_eventexposureinjuryrow6": "titorkrmf",
    "if_due_to_exposure_event_or_injury_please_specify_eg_agent_orange_radiation_burn_pitsrow6": "gkroeoenf",
    "current_disabilityiesrow7": "DIABETES",
    "approximate_date_disabilityies_began_or_worsenedrow7": "2010-2012",
    "explain_how_the_disabilityies_relates_to_the_inservice_eventexposureinjuryrow7": "dirotkfnf",
    "if_due_to_exposure_event_or_injury_please_specify_eg_agent_orange_radiation_burn_pitsrow7": "gnfoeoeid",
    "current_disabilityiesrow8": "DEPRESSION",
    "approximate_date_disabilityies_began_or_worsenedrow8": "2008-2010",
    "explain_how_the_disabilityies_relates_to_the_inservice_eventexposureinjuryrow8": "fitotntnf",
    "if_due_to_exposure_event_or_injury_please_specify_eg_agent_orange_radiation_burn_pitsrow8": "fieoekenf",
    "current_disabilityiesrow9": "NERVE DAMAGE",
    "approximate_date_disabilityies_began_or_worsenedrow9": "2007-2008",
    "explain_how_the_disabilityies_relates_to_the_inservice_eventexposureinjuryrow9": "fifoynnfkfid",
    "if_due_to_exposure_event_or_injury_please_specify_eg_agent_orange_radiation_burn_pitsrow9": "firoeotny u row",
    "current_disabilityiesrow10": "GERD (ACID REFLUX)",
    "approximate_date_disabilityies_began_or_worsenedrow10": "2004-2006",
    "explain_how_the_disabilityies_relates_to_the_inservice_eventexposureinjuryrow10": "djfifnybjfkd",
    "if_due_to_exposure_event_or_injury_please_specify_eg_agent_orange_radiation_burn_pitsrow10": "girorkdkdi",
    "current_disabilityiesrow11": "CANCER",
    "approximate_date_disabilityies_began_or_worsenedrow11": "2002-2004",
    "explain_how_the_disabilityies_relates_to_the_inservice_eventexposureinjuryrow11": "dhdisoekjr",
    "if_due_to_exposure_event_or_injury_please_specify_eg_agent_orange_radiation_burn_pitsrow11": "furorngbgndidj",
    "current_disabilityiesrow12": "IBS (IRRITABLE BOWEL SYNDROME)",
    "approximate_date_disabilityies_began_or_worsenedrow12": "2000-2002",
    "explain_how_the_disabilityies_relates_to_the_inservice_eventexposureinjuryrow12": "dhxiwkjdbfbf",
    "if_due_to_exposure_event_or_injury_please_specify_eg_agent_orange_radiation_burn_pitsrow12": "djdidjfbjodod",
    "brief_description_of_the_traumatic_events_number_1": "foforkjtbfnjf",
    "location_of_the_traumatic_events_number_1": "Afghan",
    "dates_the_traumatic_events_occured_year_number_1": "09/09/2025",
    "brief_description_of_the_traumatic_events_number_2": "dowooworotjtndkwod",
    "location_of_the_traumatic_events_number_2": "Vietnam",
    "dates_the_traumatic_events_occured_year_number_2": "10/10/1992",
    "sinus_runnyNose": "Runny nose",
    "sinus_complainedWhileInService": "yes",
    "sinus_exposedToBurnPits": "Fuels",
    "sinus_symptomsStartDate": "12/10/1997",
    "sinus_symptomsFrequency": "Seasonally",
    "sinus_dailyMedication": "yes",
    "sinus_officiallyDiagnosed": "yes",
    "sinus_treatmentProvided": "Medications",
    "sinus_details": "ggdujjiyfdbjokh",
    "tinnitus_protectionDate": "12/10/1997",
    "tinnitus_protectionDetails": "djdoxjenfjd",
    "tinnitus_exposed": "Weapons",
    "tinnitus_protection": "yes",
    "tinnitus_protectionType": "Seasonally",
    "tinnitus_protectionSickCall": "yes",
    "gerd_symptomsDate": "07/01/2000",
    "gerd_sickCallDetails": "dodornfnfjkdoff",
    "gerd_symptoms": "Acid rising in throat",
    "gerd_symptomsOften": "Seasonally",
    "gerd_medication": "yes",
    "gerd_sickCall": "yes",
    "body_role": "colonel",
    "body_responsibilities": "firorojfnr",
    "body_shiftsDuration": "1200",
    "body_injuriesDetails": "fidoeibtbtb",
    "body_physicalDetails": "wowoolktgujbvhj",
    "body_walkingDetails": "eueowpkdkd",
    "body_giveUpHobbiesDetails": "eoeoowkrjd",
    "body_jointsDetails": "oeowodkdjd",
    "body_training": "yes",
    "body_trainingTime": "5-6 times",
    "body_injuries": "yes",
    "body_sickInjuries": "yes",
    "body_discharge": "yes",
    "body_medications": "yes",
    "body_surgeries": "yes",
    "body_motion": "yes",
    "body_instability": "yes",
    "body_chronic": "yes",
    "body_tasks": "yes",
    "body_physical": "yes",
    "body_walking": "yes",
    "body_giveUpHobbies": "yes",
    "body_joints": "yes",
    "body_tingling": "yes",
    "body_sensation": "yes",
    "body_stuck": "yes",
    "body_quality": "yes",
    "others_symptomsDate": "12/01/2001",
    "others_sickCallDetails": "didorjgngnrodisoie",
    "others_symptoms": "[\"Cancer\",\"Diabetes\"]",
    "others_medication": "yes",
    "others_sickCall": "yes",
    "mental_motivatingYourself_yes": true,
    "mental_motivatingYourself_no": false,
    "mental_dailyTasksChores_yes": false,
    "mental_dailyTasksChores_no": true,
    "mental_gettingOutOfBed_yes": true,
    "mental_gettingOutOfBed_no": false,
    "mental_procrastinate_yes": false,
    "mental_procrastinate_no": true,
    "mental_isolateYourself_yes": true,
    "mental_isolateYourself_no": false,
    "mental_goingOutInPublic_yes": false,
    "mental_goingOutInPublic_no": true,
    "mental_exitsEntrances_yes": true,
    "mental_exitsEntrances_no": false,
    "mental_alwaysOnGuard_yes": false,
    "mental_alwaysOnGuard_no": true,
    "mental_racingBrain_yes": true,
    "mental_racingBrain_no": false,
    "mental_nightmares_yes": false,
    "mental_nightmares_no": true,
    "mental_exhaustedFoggy_yes": true,
    "mental_exhaustedFoggy_no": false,
    "mental_irritable_yes": false,
    "mental_irritable_no": true,
    "mental_snapEasily_yes": true,
    "mental_snapEasily_no": false,
    "mental_avoidPeople_yes": false,
    "mental_avoidPeople_no": true,
    "mental_useSubstances_yes": true,
    "mental_useSubstances_no": false,
    "mental_feelBurden_yes": false,
    "mental_feelBurden_no": true,
    "mental_questionPurpose_yes": true,
    "mental_questionPurpose_no": false,
    "mental_dealWithIssues_yes": false,
    "mental_dealWithIssues_no": true,
    "mental_medicalVisits_yes": true,
    "mental_medicalVisits_no": false,
    "mental_occupationalChange_yes": false,
    "mental_occupationalChange_no": true,
    "mental_leaveUse_yes": true,
    "mental_leaveUse_no": false,
    "mental_performanceChange_yes": false,
    "mental_performanceChange_no": true,
    "mental_depressionEpisodes_yes": true,
    "mental_depressionEpisodes_no": false,
    "mental_medicationUse_yes": false,
    "mental_medicationUse_no": true,
    "mental_disciplinaryIssues_yes": true,
    "mental_disciplinaryIssues_no": false,
    "mental_pregnancyTests_yes": false,
    "mental_pregnancyTests_no": true,
    "mental_socialBehavior_yes": true,
    "mental_socialBehavior_no": false,
    "mental_relationshipChange_yes": false,
    "mental_relationshipChange_no": true,
    "mental_jobRole": "Lieutenant ",
    "mental_hours": "1500",
    "mental_stressLevel": "very high",
    "mental_roleAndDuties": "dkdosojdhjd",
    "mental_deployArea": "Afghan ",
    "mental_deployType": "12",
    "mental_deployDetails": "djdidkfnbfgbjd",
    "mental_passAwayDetails": "didiejfnjrjf",
    "mental_naturalDate": "12/10/2000",
    "mental_naturalName": "mama jor",
    "mental_naturalDetails": "disokfbf fjfif",
    "mental_abusedDate": "12/10/1991",
    "mental_abusedName": "sergent hamma",
    "mental_abusedDetails": "didokfnfjd",
    "mental_jobDate": "12/06/1991",
    "mental_jobDetails": "fieidndjdiidbdr",
    "mental_medicalDate": "12/10/1969",
    "mental_medicalDetails": "didijdkdkdjdjd",
    "mental_medicalLocation": "vietnam",
    "mental_crashDate": "12/10/1994",
    "mental_crashLocation": "lebanon",
    "mental_crashName": "hamma yo",
    "mental_crashDetails": "sidjdhbfjjr",
    "mental_traumaDate": "12/10/1981",
    "mental_traumaLocation": "syria",
    "mental_traumaName": "doc joe hama",
    "mental_traumaDetails": "djeinfkfbf fg",
    "mental_hazingDate": "",
    "mental_hazingLocation": "",
    "mental_hazingName": "",
    "mental_hazingDetails": "",
    "mental_superiorDate": "",
    "mental_superiorLocation": "",
    "mental_superiorName": "",
    "mental_superiorDetails": "",
    "mental_dangerousDate": "",
    "mental_dangerousLocation": "",
    "mental_dangerousName": "",
    "mental_dangerousDetails": "",
    "mental_familialDate": "",
    "mental_familialLocation": "",
    "mental_familialName": "",
    "mental_familialDetails": "",
    "mental_stress": "10: extremely high stress",
    "mental_deployed": "yes",
    "mental_passAway": "yes",
    "mental_passAwayType": "suicide",
    "mental_passAwayRelation": "service member",
    "mental_naturalDisaster": "yes",
    "mental_naturalDisasterType": "combat zone",
    "mental_abused": "yes",
    "mental_abusedType": "assault abuse",
    "mental_job": "yes",
    "mental_jobType": "Weapon-related risk",
    "mental_medical": "yes",
    "mental_medicalType": "Accident",
    "mental_crash": "yes",
    "mental_crashType": "Airplane Crash",
    "mental_traumas": "yes",
    "mental_traumasTypes": "botched surgeries",
    "mental_hazing": "no",
    "mental_superior": "no",
    "mental_superiorTypes": "",
    "mental_dangerous": "no",
    "mental_dangerousTypes": "",
    "mental_familial": "no",
    "mental_familialTypes": "",
    "behavioral_changes_experienced_following_the_traumatic_event_1": "yes",
    "behavioral_changes_experienced_following_the_traumatic_event_5": "yes",
    "behavioral_changes_experienced_following_the_traumatic_event_7": "yes",
    "pregnancy_tests_around_the_time_of_the_traumatic_events": "yes",
    "economic_or_social_behavioral_changes": "yes",
    "was_an_official_report_field_YES": "yes",
    "was_an_official_report_field_RESTRICTED": "yes",
    "was_an_official_report_field_POLICE REPORT": "yes",
    "iii_11_police_report_descrption": "djeidjf",
    "a_rape_crisis_center_or_center_for_domestic_abuse": "yes",
    "a_counseling_facility_or_health_clinic": "yes",
    "a_faculty_member": "yes",
    "civilian_police_reports": "yes",
    "have_you_received_treatment_related_to_the_impact_of_the_traumatic_event_listed_in_item_9a_1": "yes",
    "va_vet_center": "yes",
    "community_care": "yes",
    "13c_name_and_location_of_the_treatment_facility_row1": "peoples health",
    "date_of_treatment_month1": "11",
    "date_of_treatment_year1": "2015",
    "13c_name_and_location_of_the_treatment_facility_row2": "angel healthcare",
    "date_of_treatment_month2": "12",
    "date_of_treatment_year2": "2020",
    "from_month_4": "9",
    "from_day_4": "11",
    "from_year_4": "2001",
    "to_month_4": "9",
    "to_day_4": "11",
    "to_year_4": "2004",
    "did_you_serve_in_a_gulf_war_hazard_location_yes": "yes",
    "location_from_month": "11",
    "location_from_year": "1975",
    "location_to_month": "12",
    "location_to_year": "1980",
    "herbicide_yes": "yes",
    "location_from_month2": "1",
    "location_from_year2": "1980",
    "location_to_month2": "1",
    "location_to_year2": "1985",
    "been_exposed_radiation": "yes",
    "the_reserves_or_national_guard_yes": "yes",
    "component_reserves_2": "yes",
    "from_month_5": "02",
    "from_day_5": "31",
    "from_year_5": "2005",
    "to_month_5": "2",
    "to_day_5": "30",
    "to_year_5": "2010",
    "21d_current_or_last_assigned_name_and_address_of_unit": "black tiger squad, hells avenue",
    "21e_current_or_assigned_phone_number_of_unit_include_area_code": "000000000000000000000000000000000000000+0000",
    "21f_training_pay_yes": "yes",
    "account_number": "",
    "account_number_checkings": "",
    "account_number_savings": "",
    "bank_name": "",
    "bank_routing_number": ""
}